#!/usr/bin/env python3

"""
===============================================================================
NGAO / GOADI FIGURE GENERATION
===============================================================================

Purpose
-------
Create time-series figures for the Northern Gulf of Alaska Oscillation (NGAO)
and Gulf of Alaska Downwelling Index (GOADI).

This script reads the index products generated by:

    src/goa_indices/indices.py

and writes figures to:

    outputs/figures/

Input files
-----------
outputs/indices/NGAO_monthly.csv
outputs/indices/GOADI_monthly.csv

Output files
------------
outputs/figures/NGAO_monthly.png
outputs/figures/GOADI_monthly.png

Plotting convention
-------------------
The plotting style follows the original NGAO/GOADI figure script:

    - black line for the index;
    - black horizontal zero line;
    - positive anomalies filled in yellow;
    - negative anomalies filled in blue;
    - yearly labels on the x-axis.

The scientific calculation is NOT performed here. This module only reads
the already-computed index values and creates figures.

===============================================================================
"""

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# =============================================================================
# PROJECT PATHS
# =============================================================================

# This file is:
#
#     repository_root/src/goa_indices/plotting.py
#
# Therefore parents[2] corresponds to the repository root.
PROJECT_ROOT = Path(__file__).resolve().parents[2]


# -----------------------------------------------------------------------------
# Input directory
# -----------------------------------------------------------------------------

INDEX_DIR = (
    PROJECT_ROOT
    / "outputs"
    / "indices"
)


# -----------------------------------------------------------------------------
# Output directory
# -----------------------------------------------------------------------------

FIGURE_DIR = (
    PROJECT_ROOT
    / "outputs"
    / "figures"
)


# -----------------------------------------------------------------------------
# Input files
# -----------------------------------------------------------------------------

NGAO_FILE = (
    INDEX_DIR
    / "NGAO_monthly.csv"
)

GOADI_FILE = (
    INDEX_DIR
    / "GOADI_monthly.csv"
)


# =============================================================================
# PLOTTING SETTINGS
# =============================================================================

# Preserve the general appearance of the original figures.
#
# Use a generic sans-serif family rather than requiring Arial specifically.
# This makes the figure reproducible on Linux runners, containers, and other
# systems where Arial may not be installed.
plt.rcParams.update(
    {
        "font.family": "sans-serif",
        "font.weight": "bold",
        "font.size": 16,
    }
)


# =============================================================================
# LOAD INDEX DATA
# =============================================================================

def load_indices():
    """
    Load NGAO and GOADI monthly index files.

    Returns
    -------
    dataframe : pandas.DataFrame

        Columns:

            date
            NGAO
            GOADI
    """

    print("\nLoading index files...")

    print(f"  NGAO : {NGAO_FILE}")
    print(f"  GOADI: {GOADI_FILE}")


    # -------------------------------------------------------------------------
    # Check that the files exist before attempting to read them.
    # -------------------------------------------------------------------------

    for path in [
        NGAO_FILE,
        GOADI_FILE,
    ]:

        if not path.exists():

            raise FileNotFoundError(
                f"Required index file does not exist:\n"
                f"  {path}\n\n"
                f"Run the index calculation first:\n"
                f"  python -m src.goa_indices.indices"
            )


    # -------------------------------------------------------------------------
    # Read CSV files.
    # -------------------------------------------------------------------------

    ngao = pd.read_csv(
        NGAO_FILE
    )

    goadi = pd.read_csv(
        GOADI_FILE
    )


    # -------------------------------------------------------------------------
    # Validate required columns.
    # -------------------------------------------------------------------------

    if not {
        "date",
        "NGAO",
    }.issubset(
        ngao.columns
    ):

        raise ValueError(
            f"{NGAO_FILE} must contain columns "
            "'date' and 'NGAO'."
        )


    if not {
        "date",
        "GOADI",
    }.issubset(
        goadi.columns
    ):

        raise ValueError(
            f"{GOADI_FILE} must contain columns "
            "'date' and 'GOADI'."
        )


    # -------------------------------------------------------------------------
    # The two index files must describe exactly the same months.
    # -------------------------------------------------------------------------

    if not np.array_equal(
        ngao["date"].values,
        goadi["date"].values,
    ):

        raise ValueError(
            "NGAO and GOADI files do not contain "
            "the same monthly date axis."
        )


    # -------------------------------------------------------------------------
    # Combine into one dataframe.
    # -------------------------------------------------------------------------

    dataframe = pd.DataFrame(
        {
            "date": pd.to_datetime(
                ngao["date"],
                format="%Y-%m",
            ),
            "NGAO": ngao["NGAO"].values,
            "GOADI": goadi["GOADI"].values,
        }
    )


    print(
        f"\nNumber of months: "
        f"{len(dataframe)}"
    )

    print(
        f"First month     : "
        f"{dataframe['date'].iloc[0]:%Y-%m}"
    )

    print(
        f"Last month      : "
        f"{dataframe['date'].iloc[-1]:%Y-%m}"
    )


    return dataframe


# =============================================================================
# CREATE ONE INDEX FIGURE
# =============================================================================

def plot_index(
    dataframe,
    column,
    ylabel,
    filename,
):
    """
    Plot one NGAO/GOADI index time series.

    Parameters
    ----------
    dataframe : pandas.DataFrame
        Dataframe containing the date and index columns.

    column : str
        Name of the index column to plot.

    ylabel : str
        Y-axis label.

    filename : pathlib.Path
        Destination PNG file.
    """

    dates = dataframe["date"]

    values = dataframe[
        column
    ].to_numpy()


    # -------------------------------------------------------------------------
    # Create figure.
    #
    # Original script used figsize=(22, 4). Keep that aspect ratio.
    # -------------------------------------------------------------------------

    fig, ax = plt.subplots(
        figsize=(22, 4)
    )


    # -------------------------------------------------------------------------
    # Index line.
    # -------------------------------------------------------------------------

    ax.plot(
        dates,
        values,
        color="black",
        linewidth=1.2,
    )


    # -------------------------------------------------------------------------
    # Zero reference line.
    # -------------------------------------------------------------------------

    ax.axhline(
        0,
        color="black",
        linewidth=1,
    )


    # -------------------------------------------------------------------------
    # Preserve original color convention:
    #
    #     positive = yellow
    #     negative = blue
    #
    # Using where= is simpler than constructing separate positive/negative
    # arrays, but produces the same visual result as the original script.
    # -------------------------------------------------------------------------

    ax.fill_between(
        dates,
        0,
        values,
        where=values > 0,
        color="yellow",
        alpha=0.6,
        interpolate=True,
    )


    ax.fill_between(
        dates,
        0,
        values,
        where=values < 0,
        color="blue",
        alpha=0.6,
        interpolate=True,
    )


    # -------------------------------------------------------------------------
    # Axis labels.
    # -------------------------------------------------------------------------

    ax.set_ylabel(
        ylabel
    )


    # -------------------------------------------------------------------------
    # Put one x-axis tick per year.
    #
    # The original script used every 12th monthly value. We preserve the same
    # annual labeling concept, but now use actual datetime coordinates.
    # -------------------------------------------------------------------------

    yearly_dates = dataframe.loc[
        dataframe["date"].dt.month == 1,
        "date",
    ]


    ax.set_xticks(
        yearly_dates
    )


    ax.set_xticklabels(
        [
            date.strftime("%Y")
            for date in yearly_dates
        ],
        rotation=70,
    )


    # -------------------------------------------------------------------------
    # Keep margins tight but avoid cutting tick labels.
    # -------------------------------------------------------------------------

    fig.tight_layout()


    # -------------------------------------------------------------------------
    # Save figure.
    # -------------------------------------------------------------------------

    filename.parent.mkdir(
        parents=True,
        exist_ok=True,
    )


    fig.savefig(
        filename,
        dpi=200,
        bbox_inches="tight",
    )


    plt.close(
        fig
    )


    print(
        f"Saved: {filename}"
    )


# =============================================================================
# MAIN WORKFLOW
# =============================================================================

def main():
    """
    Generate NGAO and GOADI monthly index figures.
    """

    print("=" * 72)

    print(
        "NGAO / GOADI FIGURE GENERATION"
    )

    print("=" * 72)


    # -------------------------------------------------------------------------
    # 1. Load index values.
    # -------------------------------------------------------------------------

    dataframe = load_indices()


    # -------------------------------------------------------------------------
    # 2. Create output directory.
    # -------------------------------------------------------------------------

    FIGURE_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )


    # -------------------------------------------------------------------------
    # 3. NGAO figure.
    # -------------------------------------------------------------------------

    plot_index(
        dataframe=dataframe,
        column="NGAO",
        ylabel="NGAO index",
        filename=(
            FIGURE_DIR
            / "NGAO_monthly.png"
        ),
    )


    # -------------------------------------------------------------------------
    # 4. GOADI figure.
    # -------------------------------------------------------------------------

    plot_index(
        dataframe=dataframe,
        column="GOADI",
        ylabel="GOADI index",
        filename=(
            FIGURE_DIR
            / "GOADI_monthly.png"
        ),
    )


    print(
        "\nFigure generation complete."
    )


if __name__ == "__main__":
    main()
